# Generated by Django 6.0 on 2025-12-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('create', 'create'), ('success', 'success'), ('failed', 'failed')], default='create', max_length=10),
        ),
    ]
