# Generated by Django 6.0 on 2025-12-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_order_statu_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statu',
            new_name='status',
        ),
    ]
