# Generated by Django 6.0 on 2025-12-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_veg',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('is_veg', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='food.recipe')),
                ('recipetype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.recipetype')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='recipevariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.recipevariant'),
        ),
    ]
